name: SummerCash
version: 0.1
description: Minecraft plugin implementation of the SummerCash protocol.
author: xoreo
website: https://github.com/SummerCash/mc-summercash/

main: com.summercash.mcsummercash.plugin.SummerCashPlugin

commands:
  test:
    description: A command used for testing.
    usage: /test
  account:
    description: Make a new SummerCash account.
    usage: /account
  transaction:
    description: Make a new transaction
    usage: /transaction <sender address> <recipient address> <amount>
  balance:
    description: Check the balance of an account
    usage: /balance

permissions: {}