name: SummerCash
version: 1.0
description: Minecraft plugin implementation of the SummerCash protocol.
author: xoreo
website: https://github.com/SummerCash/mc-summercash/

main: com.summercash.mcsummercash.plugin.SummerCashPlugin

commands:
  account:
    description: Make a new SummerCash account.
    usage: /account
  login:
    description: Login to a summer.cash account.
    usage: /login <username> <password>
  sendcash:
    description: Make a new SummerCash transaction
    usage: /sendcash <recipient address> <amount>
  bank:
    description: Check the balance of your account
    usage: /bank

permissions: {}
